# Generated by Django 3.2.14 on 2023-02-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='lid',
        ),
    ]
