# Generated by Django 3.2.14 on 2023-04-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
