# Generated by Django 3.2.14 on 2023-04-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doseinfo',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
