# Generated by Django 3.2.14 on 2023-04-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_doseinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcondition',
            name='cholestrol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='diabetes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
    ]
