# Generated by Django 3.2.14 on 2023-04-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20230411_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcondition',
            name='hd',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
