# Generated by Django 3.2.14 on 2023-04-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_medicalcondition_hd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcondition',
            name='hd',
        ),
        migrations.AddField(
            model_name='healthdetails',
            name='hd',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
