# Generated by Django 3.2.14 on 2023-04-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20230411_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcondition',
            name='cholestrol',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='diabetes',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='pressure',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
