# Generated by Django 3.2.14 on 2023-04-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20230411_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdetails',
            name='gweight',
        ),
    ]
