# Generated by Django 3.2.14 on 2023-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_reviewrating_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcalories',
            name='carbs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcalories',
            name='fats',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcalories',
            name='fiber',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcalories',
            name='proteins',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
