# Generated by Django 3.2.14 on 2023-04-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20230420_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdetails',
            name='hd',
        ),
    ]
