# Generated by Django 3.2.14 on 2023-04-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_remove_healthdetails_hd'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='lid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='health.login'),
            preserve_default=False,
        ),
    ]
