# Generated by Django 3.2.14 on 2023-04-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_nutritionist_lid'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('date', models.DateField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='health.login')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='health.login')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.login'),
        ),
        migrations.DeleteModel(
            name='calories',
        ),
    ]
