# Generated by Django 3.2.14 on 2023-05-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_auto_20230428_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
